OUTPUT	sh.abs
INPUT	..\..\lib\strt1_h.obj
INPUT	..\..\lib\strt2_h.obj
INPUT	..\..\per\smpclib\per_x1.obj
INPUT	..\..\per\smpclib\per_x2.obj
INPUT	..\..\per\smpclib\per_x3.obj
INPUT	main.obj
library	..\..\..\segalib\lib\sega_adp.lib
library	..\..\..\segalib\lib\sega_cdc.lib
library	..\..\..\segalib\lib\sega_per.lib
library	..\..\..\segalib\lib\sega_gfs.lib
library	..\..\..\segalib\lib\sega_stm.lib
library	..\..\..\segalib\lib\sega_pcm.lib
library	..\..\..\segalib\lib\sega_sys.lib
library	..\..\..\segalib\lib\sega_int.lib
library	..\..\..\segalib\lib\sega_dma.lib
library	..\..\..\segalib\lib\sega_scl.lib
library	..\..\..\segalib\lib\sega_spr.lib
library	..\..\..\segalib\lib\sega_mth.lib
library	..\..\..\segalib\lib\sega_snd.lib
library	..\..\..\segalib\lib\sega_csh.lib
library	..\..\..\sh\lib\shcnpic.lib
ENTRY	START
START	P,SEGA_P,C,SEGA_C,D,SEGA_D,B,SEGA_B(06010000)
PRINT	sh.map
EXIT
