;=======================================================================
;	smpsys.sub -- Subcommand File for SH Linkage Editor
;	Copyright(c) 1994 SEGA
;	Written by M.K on 1994-11-11(Ver.1.10)
;	èCê≥ by A.H on 1997-07-04(Ver.1.20)  MACH,MACLÉåÉWÉXÉ^ë“îÇ÷ÇÃëŒâû
;=======================================================================
Input	sys_id.obj
Input	..\..\segalib\lib\sys_sec.obj
Input	..\..\segalib\lib\sys_arej.obj
Input	..\..\segalib\lib\sys_aret.obj
Input	..\..\segalib\lib\sys_areu.obj
Input	..\..\segalib\lib\sys_aree.obj
Input   ..\..\segalib\lib\sys_init.obj
Input   main.obj
Library ..\..\segalib\lib\sega_sys.lib
Library ..\..\segalib\lib\sega_cdc.lib
STart   SYSID(06002000)
Output  ip_sh.abs
Print	ip_sh.map
EXIt
;====== End of file ====================================================
