		list	-
		opt	mcase+, hi+
		inform	0,"SNASM assembler version 2.02 HITACHI compatibility macros"
*
*		SNASM2 - Hitachi SH2 Compatibility Macros
*
*	by Hans B Pufal 8 Nov 1994
*
*
*	These macros are provided to support source code written for the
*	Hitachi SH Series Cross Assembler. The facilities are based upon
*	document HS0700ASCU1SE.

*****************************************************************************

*	This section will document the known incompatibilities between
*	SNASM2 with these macros and the Hitachi syntax.

*	1). Literal pool output.
*	    The Hitachi assembler automatically outputs any literals
*	    after the slot instruction corresponding to an RTS (or RTE)
*	    instruction. In SNASM, the user must explicitly output
*	    literals using the .LITS directive.

*	    The Hitachi .NOPOOL directive is not supported, but the .POOL
*	    directive is.

*	2). Instruction literals.
*	    Being a multi pass the Hitachi assembler can determine in
*	    all cases whether a literal can be placed in an instruction
*	    or whether it needs to be put in a literal pool. The SNASM
*	    assembler is essentially a single pass and in some cases
*	    cannot do this.

*		a) Any literal which can be evaluated is correctly
*		   emitted either into the instruction or into the
*		   literal pool.

*		b) Any literal which cannot be evaluated whne the
*		   instruction is encountered will be assuimed to be
*		   too big for the instruction and will be forced into
*		   the literal pool.

*		c) If it is necessary to use a forward referenced literal
*		   which does fit into the instruction, use ## instead
*		   of # when specifying the literal to force the literal
*		   into the instruction.

*	3). In the .SECTION directive, the COMMON type is not supported.

*	4). In string directives e.g .SDATA if a control character is to
*	    be inserted use a simple literal:

*		.SDATA	"ABAB",H'07

*	    instead of the Hitachi construct

*		.SDATA	"ABAB"<H'07'>

*	5). The <lit> construct is not supported for .SDATAB, .SDATAC, or
*		.SDATAZ

*	6). The .OUPUT directive is not supported, its features are
*		availbale from command line switches.

*	6). The .DEBUG directive is not supported, its features are
*		available from command line switches.

*	7). No errors are generated if improper constructs are used in
*	    DUMMY sections.

*	8). SNASM does not support the Hitachi line continuation facility
*	    of placing a '+' at the start of the continuation line, SNASM
*	    uses an & at the end of the previous line.

*	11).Up to 10 macro parameters are supported. When refercning formal
*	    parameters in macro bodies SNASM does not support the ' at the
*	    the parameter name; SNASM can (optionally) delimit the name with
*	    a '\' character. Default parameter values are not supported and
*	    the keyword calling syntax is also not supported.

*	    Macro replacement processing exclusion construct : \(....) is
*	    not supported by SNASM

*	    All macro comments are removed during the processing of macro
*	    definitions. The \; construct is not supported.

*	12).SNASM has string manipulation functions similar to the Hitachi
*	    .LEN, .INSTR and .SUBSTR functions. The SNASM syntax is slightly
*	    different and te Hitachi syntax is not supported.

*****************************************************************************

; An auto-aligning dc.l
; ?? does the Hitachi assembler auto align longs (or words)

_.dc.l:		alias	dc.l
		disable	dc.l

dc.l:		macro	*
		cnop	0,4,0
\*:		_.dc.l	\_
		endm
		disable _.dc.l

; and one for rs.l

_.rs.l:		alias	rs.l
		disable rs.l

rs.l:		macro	*

		while	__rs&3
		rs.b	1
		endw

\*:		_.rs.l	\_
		endm

		disable _.rs.l


_.msg1		macros
		inform	1,"\1 not supported"


??dummy		equs	""


; The section directive on the Hitachi assember allows you to specify the
; type of the section and one of these types is dummy. Dummy sections are used
; in the same way that we use RS directives so we try to support this.

.section	macro	name,type,alignlocate

	local	tempstr1,tempstr2


; If we were previously in a dummy section we save away its __rs in a suitably
; name string variable.
		if	strlen("\??dummy")
??\??dummy	=	__rs
??dummy		equs	""
		endif


; This handles dummy sections
		if 	stricmp("\type","dummy")|&
			def(??\name)

; First time in section so set __rs to zero
		if	~def(??\name)
??\name	=	0
		endif

; Set __rs to correct value and set ??dummy so we know what section we
; were in.
		rsset	??\name
??dummy		equs	"\name"

		mexit
		endif


; This handles non-dummy sections
		if 	(strlen("\type")=0)|stricmp ("\type","data")|&
			stricmp ("\type","code")|stricmp ("\type","stack")

; See if this section has an align setting
tempstr1		substr	1,6,'\alignlocate'
tempstr2		substr	1,7,'\alignlocate'
		if	stricmp('\tempstr1','ALIGN=')
tempstr1		substr	7,,'\alignlocate'
		section.\tempstr1	\name
		mexit
; it doesn't so see if it uses locate
		elseif stricmp('\tempstr2','LOCATE=')
tempstr1		substr	8,,'\alignlocate'
\name		section	org(\tempstr1)
		mexit
		else
; no locate either so must be a normal section
		section.l	\name
		mexit
		endif
		endif


; This handles common sections
		if	stricmp("\2","common")
		inform	2," ".SECTION type COMMON not supported"
		mexit
		endif

		inform	2,".SECTION type '\2' not recognized"

		endm



.org		alias	org


.equ		alias	equ

.assign		alias	set

.reg		alias	equr

align		macros
		cnop	0,\1,0

.align		alias	align

.data		alias	dc.l

.data.l		alias	dc.l

.data.w		alias	dc.w

.data.b		alias	dc.b


.datab		macro	count,data
		rept	count
		dc.l	data
		endr
		endm

.datab.l	alias	.datab

.datab.w	macro	count,data
		rept	count
		dc.w	data
		endr
		endm

.datab.b	macro	count,data
		rept	count
		dc.b	data
		endr
		endm


.sdata		alias	dc.b


.sdatab		macro	count,string
		rept	count
		dc.b	string
		endr
		endm

.sdatac		macro
		rept	narg
		dc.b	strlen(\1), \1
		shift
		endr
		endm


.sdataz		macro
		rept	narg
		dc.b	\1,0
		shift
		endr
		endm




.res.l		macro	*
		if	strlen("\??dummy")
\*		rs.l	\1
		else
\*		ds.l	\1
		endif
		endm

.res.w		macro	*
		if	strlen("\??dummy")
\*		rs.w	\1
		else
\*		ds.w	\1
		endif
		endm

.res.b		macro	*
		if	strlen("\??dummy")
\*		rs.b	\1
		else
\*		ds.b	\1
		endif
		endm


.res		alias	.res.l


.sres		macro	*
		rept	narg
		if	strlen("\??dummy")
\*		rs.b	strlen(\1)
		else
\*		ds.b	strlen(\1)
		endif
		shift
		endr
		endm


.sresc		macro	*
		rept	narg
		if	strlen("\??dummy")
\*		rs.b	strlen(\1)+1
		else
\*		ds.b	strlen(\1)
		endif
		shift
		endr
		endm


.sresz		alias	.sresc



.export		alias	export

.import		alias	import

.global		alias	global

.output		macros
		_.msg1	.OUTPUT

.debug		macros
		_.msg1	.DEBUG

.print		macros
		_.msg1	.PRINT

.list		macros
		_.msg1	.LIST

.form		macros
		_.msg1	.FORM

.heading	macros
		_.msg1	.HEADING

.page		macros
		_.msg1	.PAGE

.space		macros
		_.msg1	.SPACE

.program	macros
		_.msg1	.PROGRAM

.radix		macro

		if strlen("\1")==0
		radix	10
		mexit
		endif

		case "\1"
='B','b'
		radix	2
		mexit

='O','o'
		radix	8
		mexit

='D','d'
		radix	10
		mexit

='H','h'
		radix	16
		mexit

=?		inform	3,"Invalid .RADIX specifier '\1'"
		endcase
		endm

.end		alias	end

.include	alias	include


.assigna	macros	*
\*		equs	\1


.assignc	alias	equs

.aif		alias	if

.aelse		alias	else

.aendi		alias	endif

.arepeat	alias	rept

.aendr		alias	endr

.awhile		alias	while

.aendw		alias	endw

.exitm		alias	mexit

.macro		macros
\1:		macro	\2,\3,\4,\5,\6,\7,\8,\9,\10

.endm		alias	endm

.lits		alias	lits
.lits.w		alias	lits.w
.lits.l		alias	lits.l

.pool		macro
		if	_litflags & (h'10 | h'4)
		bra	l_\@
		nop
		.lits
		endif
l_\@:
		endm

.pool.w		macro
		if	_litflags & h'4)
		bra	l_\@
		nop
		.lits.w
		endif
l_\@:
		endm

.pool.l		macro
		if	_litflags & h'10
		bra	l_\@
		nop
		.lits.l
		endif
l_\@:
		endm

.nopool		macros
		_.msg1	.NOPOOL

		disable	shift

		opt	mcase-
		opt	c+
		list	+

CSSC 		macro P,Q
		CLRMAC
		ADD	#\P,R7
		MAC.L	@R7+,@R5+
		ADD	#\Q-\P-4,R7
		MAC.L	@R7+,@R5+
		ADD	#-\Q+\P-4,R7
		STS	MACH,R1
		STS	MACL,R0
		CLRMAC
		MAC.L	@R7+,@R5+
		ADD	#\Q-\P-4,R7
		MAC.L	@R7+,@R5+
		ADD	#-\Q-4,R7
		XTRCT	R1,R0
		MOV.L	R0,@(\P,R7)
		ADD	#-16,R5
		STS	MACH,R3
		STS	MACL,R2
		XTRCT	R3,R2
		MOV.L	R2,@(\Q,R7)
		ENDM

M123		MACRO	 P
		CLRMAC
		ADD	#\P,R7
		MAC.L	@R7+,@R5+
		MAC.L	@R7+,@R5+
		MAC.L	@R7+,@R5+
		ADD	#-12,R5
		MOV.L	@R7,R2
		ADD	#-\P-12,R7
		STS	MACH,R1
		STS	MACL,R0
		XTRCT	R1,R0
		ADD	R2,R0
		MOV.L	R0,@(\P+12,R7)
		ENDM

T123		MACRO P
		CLRMAC
		ADD	#\P,R7
		MAC.L	@R7+,@R4+
		MAC.L	@R7+,@R4+
		MAC.L	@R7+,@R4+
		ADD	#-12,R4
		MOV.L	@R7,R2
		ADD	#-\P-12,R7
		STS	MACH,R1
		STS	MACL,R0
		XTRCT	R1,R0
		ADD	R2,R0
		MOV.L	R0,@R5
		ADD	#4,R5
		ENDM

N123		MACRO P
		CLRMAC
		ADD	#\P,R7
		MAC.L	@R7+,@R4+
		MAC.L	@R7+,@R4+
		MAC.L	@R7+,@R4+
		ADD	#-12,R4
		ADD	#-\P-12,R7
		STS	MACH,R1
		STS	MACL,R0
		XTRCT	R1,R0
		MOV.L	R0,@R5
		ADD	#4,R5
		ENDM

PROD		MACRO RP,RQ,RR
		CLRMAC
		MAC.L	@\RP+,@\RQ+
		MAC.L	@\RP+,@\RQ+
		MAC.L	@\RP+,@\RQ+
		ADD	#-12,\RP
		ADD	#-12,\RQ
		STS	MACH,R0
		STS	MACL,\RR
		XTRCT	R0,\RR
		ENDM

