LIBRARY ..\..\..\segalib\lib\sega_mth.lib
LIBRARY ..\..\..\segalib\lib\sega_spr.lib
LIBRARY ..\..\..\segalib\lib\sega_scl.lib
LIBRARY ..\..\..\segalib\lib\sega_dma.lib
LIBRARY ..\..\..\segalib\lib\sega_csh.lib
LIBRARY ..\..\..\segalib\lib\sega_cdc.lib
LIBRARY ..\..\..\segalib\lib\sega_gfs.lib
LIBRARY ..\..\..\segalib\lib\sega_stm.lib
LIBRARY ..\..\..\segalib\lib\sega_snd.lib
LIBRARY ..\..\..\segalib\lib\sega_cpk.lib
LIBRARY ..\..\..\segalib\lib\sega_dbg.lib
LIBRARY ..\..\..\segalib\lib\sega_per.lib
LIBRARY ..\..\..\segalib\lib\sega_int.lib
LIBRARY ..\..\..\segalib\lib\sega_sys.lib
LIBRARY ..\..\..\sh\lib\shcnpic.lib
OUTPUT sh.abs
PRINT  sh.map
INPUT ..\..\..\segasmp\lib\strt1_h.obj
INPUT ..\..\..\segasmp\lib\strt2_h.obj
INPUT ..\..\..\segasmp\per\smpclib\per_x1.obj
INPUT ..\..\..\segasmp\per\smpclib\per_x2.obj
INPUT ..\..\..\segasmp\per\smpclib\per_x3.obj
INPUT main.obj
START P,SEGA_P,C,SEGA_C,D,B,SEGA_B(06010000)
FORM A
EXIT
