#define	MAP_HSIZE	20
#define	MAP_VSIZE	1
#define	MAP_UNIT	2048L

#define	S2D_PNBSIZE	(PNB_1WORD|CN_12BIT)
#define	S2D_COLTYPE	COL_TYPE_16
#define	S2D_CHRSIZE	CHAR_SIZE_2x2


#define	S2D_CELSIZE	39936L

#define	S2D_MAP	map_pine
#define	S2D_CEL	cel_pine
#define	S2D_PAL	pal_pine

extern Uint16	map_pine[];
extern Uint16	cel_pine[];
extern Uint16	pal_pine[];

#define	S2D_PALSIZE	32L


