;****************************************************************
;	Saturn Sample Program
;	Master sh2 global variable externs
;
;	Copyright SEGA of America inc. 1994
;---------------------------------------------------------------*
;****************************************************************

		
	xref	sintbl
	xref	sintblend

	xref	intmask
	xref	vcounter
	xref	pad0, pad1
	xref	numsprites
	xref	lastsprite

	xref	Mstack


	xref	camerax, cameray, cameraz
	xref	xangle, yangle, zangle
