cd DEMO_A
call mk.bat
PAUSE
cd ..\DEMO_B
call mk.bat
PAUSE
cd ..\DEMO_C
call mk.bat
PAUSE
cd ..\S_2_2
call mk.bat
PAUSE
cd ..\S_3_2
call mk.bat
PAUSE
cd ..\S_4_2
call mk.bat
PAUSE
cd ..\S_4_3_1
call mk.bat
PAUSE
cd ..\S_4_3_2
call mk.bat
PAUSE
cd ..\S_4_3_3
call mk.bat
PAUSE
cd ..\S_4_3_4
call mk.bat
PAUSE
cd ..\S_4_5
call mk.bat
PAUSE
cd ..\S_5_2
call mk.bat
PAUSE
cd ..\S_6_3
call mk.bat
PAUSE
cd ..\S_7_2
call mk.bat
PAUSE
cd ..\S_7_4
call mk.bat
PAUSE
cd ..\S_7_6
call mk.bat
cd ..