
	if 1	
push		MACRO
		REPT	NARG

		IF	STRICMP('\1','PR')
		sts.l	PR,@-r15
		ELSEIF	STRICMP('\1','SR')
		sts.l	SR,@-r15
		ELSEIF	STRICMP('\1','VBR')
		sts.l	VBR,@-r15
		ELSEIF	STRICMP('\1','GBR')
		stc.l	GBR,@-r15
		ELSEIF	STRICMP('\1','MACH')
		sts.l	MACH,@-r15
		ELSEIF	STRICMP('\1','MACL')
		sts.l	MACL,@-r15
		ELSE
		mov.l	\1,@-r15
		ENDIF

		SHIFT

		ENDR
		ENDM

pop		MACRO
		REPT	NARG

		IF	STRICMP('\1','PR')
		lds.l	@r15+,PR
		ELSEIF	STRICMP('\1','SR')
		lds.l	@r15+,SR
		ELSEIF	STRICMP('\1','VBR')
		lds.l	@r15+,VBR
		ELSEIF	STRICMP('\1','GBR')
		ldc.l	@r15+,GBR
		ELSEIF	STRICMP('\1','MACH')
		lds.l	@r15+,MACH
		ELSEIF	STRICMP('\1','MACL')
 		lds.l	@r15+,MACL
		ELSE
		mov.l	@r15+,\1
		ENDIF

		SHIFT

		ENDR
		ENDM

;
;
;

call		MACRO	function
		IF	(TYPE(\function)=0x0400)
		mov	#\function,R0
		jsr	@R0
		nop

		ELSE
		bsr	\function
		nop
		ENDIF
		ENDM


	endif

	if 0
push	macro	reg

	if stricmp ("\reg","pr")=0
	mov.l	\reg,@-r15
	else
	sts.l	pr,@-r15	; save return address
	endif

	endm


pop	macro	reg
	mov.l	@r15+,\reg
	endm

call	macro	func
	mov.l	#\func,r0
	jsr	@r0
	nop
	endm

	
	endif
