#include <machine.h>
#include <string.h>
#define _SH
#include "sega_xpt.h"
#include "sega_sys.h"
#include "sega_int.h"
#include "sega_per.h"
#include "sega_cdc.h"
#include "sega_gfs.h"
#include "sega_stm.h"
#include "sega_snd.h"
#include "sega_pcm.h"

#if	1
	/*
	**¡1995-07-28	‚‹´’q‰„
	**	SCL_VblankStart(), SCL_VBlankEnd() ‚ğg‚Á‚Ä‚¢‚é‚Ì‚Å’Ç‰Á
	*/
	#include	"sega_scl.h"
#endif
