/********************************************************************
*  FILE:    smperm12.h
*
*   Copyright(c) 1996 SEGA
*
*  PURPOSE:
*   「拡張RAMライブラリ」テストプログラム
*
*  AUTHOR(S):
*   H.K
*
*  MOD HISTORY:
*   Written by H.K on 1997-06-03 Ver.1.11
********************************************************************/
#ifndef _SMPERM02_H_
#define _SMPERM02_H_
#include "sega_xpt.h"

void    DispInit(void);


#endif