/********************************************************************
*  FILE:    smperm10.h
*
*   Copyright(c) 1996 SEGA
*
*  PURPOSE:
*   「拡張RAMライブラリ」テストプログラム
*
*  AUTHOR(S):
*   H.K
*
*  MOD HISTORY:
*   Written by H.K on 1997-06-03 Ver.1.11
********************************************************************/
#ifndef _SMPERM01_H_
#define _SMPERM01_H_


enum{
    INIT,
    MAIN
    };

extern Uint8 Level;

#endif