#define	MAP_HSIZE	1
#define	MAP_VSIZE	1
#define	MAP_UNIT	4096L

#define	S2D_PNBSIZE	PNB_2WORD
#define	S2D_COLTYPE	COL_TYPE_256
#define	S2D_CHRSIZE	CHAR_SIZE_2x2
#define	S2D_CELSIZE	103168L

#define	S2D_MAP	map_flower
#define	S2D_CEL	cel_flower
#define	S2D_PAL	pal_flower

extern Uint32	map_flower[];
extern Uint16	cel_flower[];
extern Uint16	pal_flower[];

#define	S2D_PALSIZE	512L


