;------------------------------------------------------------------------------
;  smpspr2.sub -- PC 用 スプライトサンプル２ LNK パラメータファイル
;  Copyright(c) 1994 SEGA
;  Written by H.E on 1994-02-15 Ver.0.80
;  Updated by K.M on 1994-05-10 Ver.0.80
;------------------------------------------------------------------------------
;
library	..\..\segalib\lib\sega_erm.lib
library	..\..\segalib\lib\sega_adp.lib
library	..\..\segalib\lib\sega_bpl.lib
library	..\..\segalib\lib\sega_cdc.lib
library	..\..\segalib\lib\sega_cmp.lib
library	..\..\segalib\lib\sega_csh.lib
library	..\..\segalib\lib\sega_dbg.lib
library	..\..\segalib\lib\sega_dma.lib
library	..\..\segalib\lib\sega_dsp.lib
library	..\..\segalib\lib\sega_gfs.lib
library	..\..\segalib\lib\sega_mem.lib
library	..\..\segalib\lib\sega_mpg.lib
library	..\..\segalib\lib\sega_mth.lib
library	..\..\segalib\lib\sega_pcm.lib
library	..\..\segalib\lib\sega_sys.lib
library	..\..\segalib\lib\sega_per.lib
library	..\..\segalib\lib\sega_scl.lib
library	..\..\segalib\lib\sega_snd.lib
library	..\..\segalib\lib\sega_spr.lib
library	..\..\segalib\lib\sega_stm.lib
library	..\..\segalib\lib\sega_sgl.lib
library	..\..\segalib\lib\sega_int.lib
LIBRARY ..\..\sh\lib\shcnpic.lib

;
PRINT 	game.map
;DEBUG
OUTPUT 	game.abs
INPUT	..\lib\strt1_h.obj
INPUT	..\lib\strt2_h.obj
INPUT	..\per\smpclib\per_x1.obj
INPUT	..\per\smpclib\per_x2.obj
INPUT	..\per\smpclib\per_x3.obj
INPUT	title.obj
INPUT	demo.obj
INPUT	logo.obj
INPUT	v_blank.obj
INPUT	polygon.obj
INPUT	game_sub.obj
INPUT	act.obj
INPUT	game.obj
INPUT	data.obj
INPUT	cd_ctrl.obj
INPUT	sequence.obj
START	P,SEGA_P,C,SEGA_C,D,SEGA_D,B,SEGA_B(06010000)
FORM    A
EXIT
; end of file
